export const PERMISSION_MODULES = [
  'dashboard',
  'classes',
  'admission',
  'fees',
  'invoice',
  'attendance',
  'timetable',
  'subjects',
  'homework',
  'assessment',
  'exam',
  'noticeboard',
  'notifications',
  'reports',
  'settings',
  'roles',
  'students',
  'teachers',
  'transport',
  'syllabus',
  'gallery',
  'lectures',
  'products',
  'diary',
  'holidays',
  'chat',
  'audit-logs',
];

export const PERMISSION_ACTIONS = ['view', 'create', 'edit', 'delete', 'approve', 'export'];
